# Generated by Django 4.0.3 on 2022-04-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='rating',
            field=models.IntegerField(default=60),
        ),
    ]
