# Generated by Django 4.0.3 on 2022-04-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('SPT', 'Sport'), ('SNC', 'Sience'), ('CTR', 'Culture'), ('MVE', 'Movie')], default='', max_length=3),
        ),
    ]
