# Generated by Django 4.0.3 on 2022-04-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('Sport', 'Sport'), ('Sience', 'Sience'), ('Culture', 'Culture'), ('Movie', 'Movie')], default='', max_length=30),
        ),
    ]
